manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: kumamuk-git
      url-base: https://github.com/kumamuk-git
    - name: urob
      url-base: https://github.com/urob
    - name: te9no
      url-base: https://github.com/te9no
  projects:
    - name: zmk
      remote: urob
      revision: 254f525f8043d13ac861a95ed2c13f26b5b22beb
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: kumamuk-git
      revision: 5e04553ab803d24405bd45621a41310ea3050e59
    - name: zmk-leader-key
      remote: urob
      revision: 9dce878bfd6a4a7f34d9efa8251083250c1a33a3
  self:
    path: config
